"""Task 4b - (1) Render blog/blog_post.md to a self-contained, paste-ready HTML page (images embedded) for
LinkedIn Articles / Medium, and (2) build the engagement audit report from the author-maintained engagement log.

Engagement is NEVER generated by this code: blog/engagement/engagement_log.csv must be filled by the author from
the live post (one row per external reaction/comment), with screenshots saved in blog/engagement/screenshots/.
Run again after updating the log to refresh blog/engagement/engagement_audit_report.md and the metrics JSON
used by the final video.
"""
import os, re, base64, json
import pandas as pd, markdown

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
B = os.path.join(ROOT, "blog"); E = os.path.join(B, "engagement"); os.makedirs(os.path.join(E, "screenshots"), exist_ok=True)

# ---------- (1) HTML rendering ----------
md = open(os.path.join(B, "blog_post.md"), encoding="utf-8").read()
html = markdown.markdown(md, extensions=["footnotes", "tables"])
def embed(m):
    p = os.path.join(B, m.group(1))
    return f'src="data:image/png;base64,{base64.b64encode(open(p, "rb").read()).decode()}"' if os.path.exists(p) else m.group(0)
html = re.sub(r'src="(images/[^"]+)"', embed, html)
page = f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>India's Festival Calendar in Data</title>
<style>
:root{{--bg:#fcfcfb;--ink:#0b0b0b;--ink2:#52514e;--rule:#e4e3df;--link:#256abf}}
@media (prefers-color-scheme:dark){{:root{{--bg:#1a1a19;--ink:#fff;--ink2:#c3c2b7;--rule:#383835;--link:#86b6ef}}}}
body{{background:var(--bg);color:var(--ink);font:17px/1.65 Georgia,'Times New Roman',serif;margin:0;padding:24px 16px}}
main{{max-width:760px;margin:auto}} h1{{font:700 2.1rem/1.2 'Segoe UI',Arial,sans-serif}} h2,h3{{font-family:'Segoe UI',Arial,sans-serif;margin-top:2.2em}}
img{{max-width:100%;height:auto;border-radius:6px;border:1px solid var(--rule)}} em{{color:var(--ink2)}} a{{color:var(--link)}}
table{{border-collapse:collapse;font:15px 'Segoe UI',Arial}} td,th{{border-bottom:1px solid var(--rule);padding:6px 12px;text-align:left}}
.footnote{{font-size:14px;color:var(--ink2)}} hr{{border:0;border-top:1px solid var(--rule)}}
</style></head><body><main>{html}</main></body></html>"""
open(os.path.join(B, "blog_post.html"), "w", encoding="utf-8").write(page)
print("blog_post.html written", round(len(page) / 1e6, 2), "MB")

# ---------- (2) Engagement audit ----------
LOG = os.path.join(E, "engagement_log.csv")
cols = ["timestamp", "platform", "interaction_type", "person_name", "person_headline_or_org", "is_same_institution",
        "comment_text", "author_replied", "reply_timestamp", "screenshot_file", "profile_url"]
if not os.path.exists(LOG):
    pd.DataFrame(columns=cols).to_csv(LOG, index=False)
log = pd.read_csv(LOG)
post = {}
meta_p = os.path.join(E, "post_meta.json")
if os.path.exists(meta_p): post = json.load(open(meta_p, encoding="utf-8"))
ext = log[log.is_same_institution.astype(str).str.lower().isin(["no", "false", "0", "n"])] if len(log) else log
m = {"live_url": post.get("live_url", "NOT YET PUBLISHED"), "published_on": post.get("published_on", ""),
     "total_logged_interactions": int(len(log)), "external_interactions": int(len(ext)),
     "excluded_same_institution": int(len(log) - len(ext)),
     "external_reactions": int((ext.interaction_type.str.lower() == "reaction").sum()) if len(ext) else 0,
     "external_comments": int((ext.interaction_type.str.lower() == "comment").sum()) if len(ext) else 0,
     "external_reposts_shares": int(ext.interaction_type.str.lower().isin(["repost", "share"]).sum()) if len(ext) else 0,
     "comments_with_author_reply": int(((ext.interaction_type.str.lower() == "comment") &
                                        (ext.author_replied.astype(str).str.lower().isin(["yes", "true", "1", "y"]))).sum()) if len(ext) else 0,
     "target_external": 40}
m["target_met"] = m["external_interactions"] >= 40
m["reply_rate_pct"] = round(100 * m["comments_with_author_reply"] / m["external_comments"], 1) if m["external_comments"] else None
json.dump(m, open(os.path.join(E, "engagement_metrics.json"), "w"), indent=1)
rep = ["# Engagement Audit Report\n", f"**Live URL:** {m['live_url']}  ", f"**Published on:** {m['published_on']}\n",
       "| Metric | Value |", "|---|---|"] + [f"| {k} | {v} |" for k, v in m.items() if k not in ("live_url", "published_on")]
rep += ["\n**Rules applied:** only interactions from people outside Vidyalankar Institute of Technology are counted "
        "(`is_same_institution = no`). Every row must have a screenshot in `screenshots/`.\n"]
if len(ext):
    rep += ["## External interaction log\n", ext[["timestamp", "platform", "interaction_type", "person_name", "person_headline_or_org",
                                               "author_replied", "screenshot_file"]].to_markdown(index=False)]
else:
    rep += ["_No interactions logged yet: publish the post, then record each external reaction/comment in engagement_log.csv._"]
open(os.path.join(E, "engagement_audit_report.md"), "w", encoding="utf-8").write("\n".join(rep))
print(json.dumps(m, indent=1))
